accounts/urls.py
from django.urls import path
from . import views


app_name='account'
urlpatterns = [
    path('login/',views.login_view,name="login"),
    path('signup/',views.profileregister,name="signup"),
    path('logout/',views.logout_view,name="logout"),
    path('profile/',views.profile_view,name="profile"),
    path('profileedit/',views.ProfileEdit,name='edit'),


]

api/urls.py
from django.urls import path , include
from .views import NewsList , NewsDetail, UserDetail ,UserList
from rest_framework.authtoken.views import obtain_auth_token
#from api.views import RevokeToken
# from rest_framework_simplejwt import views as jwt_views
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView


urlpatterns = [
    path("news/",NewsList.as_view(), name="list"),
    path("news/<int:pk>/",NewsDetail.as_view(), name="detail"),
    path("user/",UserList.as_view(), name="user-list"),
    path("user/<int:pk>/",UserDetail.as_view(), name="user-detail"),
    path('rest-auth/', include('dj_rest_auth.urls')),
    path('rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

]

core/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('news/',include('news.urls')),
    path('account/',include('accounts.urls')),
    #when using token we dont need this
    #path('api-auth/', include('rest_framework.urls')),
    path("api/",include("api.urls")),

]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

app_name='home'
urlpatterns = [
    path('',views.home, name='home'),
    path('contact/',views.contact,name='contact'),
    path('about/',cache_page(60 * 15)(views.about),name='about'),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('news/',views.NewsListView.as_view(), name='news'),
    path('news-detail/<int:num>/',views.NewsDetailView.as_view() , name='detail'),
    path('category/<str:name>/',views.CategoryView.as_view() , name="category"),
    path('search/',views.SearchView.as_view() , name="search"),
    path('favorite/',views.FavoriteView, name='favorite'),
    path('save_favorite/<int:post_id>/', views.save_favorite, name='save_favorite'),
    path('tags/<str:tag_name>/',views.TagView.as_view() , name='tag')

]

templates/base/base.html
{% load static %}
{% load cache %}
{% block head %}
{% endblock head%}
<body>
    {% comment %} <!-- Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'assets/img/logo/logo.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start --> {% endcomment %}
    {% cache 500 header %}
    <header>
        <!-- Header Start -->
        <div class="header-area">
            <div class="main-header ">
                <div class="header-top black-bg d-none d-sm-block">
                    <div class="container">
                        <div class="col-xl-12">
                            <div class="row d-flex justify-content-between align-items-center">
                                <div class="header-info-left">
                                    <ul>     
                                        <li class="title"><span class="flaticon-energy"></span> trending-title</li>
                                        <li>Class property employ ancho red multi level mansion</li>
                                    </ul>
                                </div>
                                <div class="header-info-right">
                                    <ul class="header-date">
                                        <li><span class="flaticon-calendar"></span> +880166 253 232</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="header-mid gray-bg">
                    <div class="container">
                        <div class="row d-flex align-items-center">
                            <!-- Logo -->
                            <div class="col-xl-3 col-lg-3 col-md-3 d-none d-md-block">
                                <div class="logo">
                                    <a href="index.html"><img src="{% static 'assets/img/logo/logo.png' %}" alt=""></a>
                                </div>
                            </div>
                            <div class="col-xl-9 col-lg-9 col-md-9">
                                <div class="header-banner f-right ">
                                    {% comment %} <img src="{% static 'assets/img/gallery/header_card.png' %}" alt=""> {% endcomment %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="header-bottom header-sticky">
                    <div class="container">
                        <div class="row align-items-center">
                            <div class="col-xl-8 col-lg-8 col-md-12 header-flex">
                                <!-- sticky -->
                                <div class="sticky-logo">
                                    <a href="index.html"><img src="{% static 'assets/img/logo/logo.png' %}" alt=""></a>
                                </div>
                                <!-- Main-menu -->
                                <div class="main-menu d-none d-md-block">
                                    <nav>                  
                                        <ul id="navigation">
                                            <li><a href="{% url "home:home" %}">Home</a></li>
                                            <li><a href="{% url "home:about" %}">about</a></li>
                                            <li><a href={% url "news:category" name='SPORT' %}>Category</a></li>

                                            <li><a href="{% url "news:news" %}">Blog</a></li>
                                            <li><a href="{% url "home:contact" %}">Contact</a></li>

                                            {% if user.is_authenticated %}
                                            <li><a href="{% url "account:profile" %}">Profile</a></li>
                                            <li><a href="{% url "account:logout" %}">Logout</a></li>
                                            {% else %}
                                            <li><a href="{% url "account:login" %}">Login</a></li>
                                            <li><a href="{% url "account:signup" %}">Sign-up</a></li>
                                            {%  endif %}
                                        </ul>
                                    </nav>
                                </div>
                            </div>             
                            <div class="col-xl-4 col-lg-4 col-md-4">
                                <div class="header-right f-right d-none d-lg-block">
                                    <!-- Heder social -->
                                    <ul class="header-social">    
                                        <li><a href="https://www.fb.com/sai4ull"><i class="fab fa-facebook-f"></i></a></li>
                                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                        <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                                        <li> <a href="#"><i class="fab fa-youtube"></i></a></li>
                                    </ul>
                                    <!-- Search Nav -->
                                    <div class="nav-search search-switch">
                                        <i class="fa fa-search"></i>
                                    </div>
                                </div>
                            </div>
                            <!-- Mobile Menu -->
                            <div class="col-12">
                                <div class="mobile_menu d-block d-md-none"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header End -->
    </header>

    {% endcache %}

{% block content%}

{% endblock content%}
<footer>
    <!-- Footer Start-->
    <div class="footer-main footer-bg">
        <div class="footer-area footer-padding">
            <div class="container">
                <div class="row d-flex justify-content-between">
                    <div class="col-xl-3 col-lg-3 col-md-5 col-sm-8">
                        <div class="single-footer-caption mb-50">
                            <div class="single-footer-caption mb-30">
                                <!-- logo -->
                                <div class="footer-logo">
                                    <a href="index.html"><img src="{% static "assets/img/logo/logo2_footer.png" %} " alt=""></a>
                                </div>
                                <div class="footer-tittle">
                                    <div class="footer-pera">
                                        <p class="info1">Lorem ipsum dolor sit amet, nsectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
                                        <p class="info2">198 West 21th Street, Suite 721 New York,NY 10010</p>
                                        <p class="info2">Phone: +95 (0) 123 456 789 Cell: +95 (0) 123 456 789</p>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-4 col-md-5 col-sm-7">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Popular post</h4>
                            </div>
                            <!-- Popular post -->
                            <div class="whats-right-single mb-20">
                                <div class="whats-right-img">
                                    <img src="{% static "assets/img/gallery/footer_post1.png" %} " alt="">
                                </div>
                                <div class="whats-right-cap">
                                    <h4><a href="details.html">Scarlett’s disappointment at latest accolade</a></h4>
                                    <p>Jhon  |  2 hours ago</p> 
                                </div>
                            </div>
                            <!-- Popular post -->
                            <div class="whats-right-single mb-20">
                                <div class="whats-right-img">
                                    <img src="{% static "assets/img/gallery/footer_post2.png" %} " alt="">
                                </div>
                                <div class="whats-right-cap">
                                    <h4><a href="details.html">Scarlett’s disappointment at latest accolade</a></h4>
                                    <p>Jhon  |  2 hours ago</p> 
                                </div>
                            </div>
                            <!-- Popular post -->
                            <div class="whats-right-single mb-20">
                                <div class="whats-right-img">
                                    <img src="{% static "assets/img/gallery/footer_post3.png" %} " alt="">
                                </div>
                                <div class="whats-right-cap">
                                    <h4><a href="details.html">Scarlett’s disappointment at latest accolade</a></h4>
                                    <p>Jhon  |  2 hours ago</p> 
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-5 col-sm-7">
                        <div class="single-footer-caption mb-50">
                            <div class="banner">
                                <img src="{% static "assets/img/gallery/body_card4.png" %} " alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- footer-bottom aera -->
        <div class="footer-bottom-area footer-bg">
            <div class="container">
                <div class="footer-border">
                        <div class="row d-flex align-items-center">
                            <div class="col-xl-12 ">
                                <div class="footer-copy-right text-center">
                                    <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End-->
</footer>
<!-- Search model Begin -->
<div class="search-model-box">
    <div class="d-flex align-items-center h-100 justify-content-center">
        <div class="search-close-btn">+</div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Searching key.....">
        </form>
    </div>
</div>
<!-- Search model end -->
{% block js %}
{% endblock js %}

templates/base/category.html
{% load static %}
<aside class="single_sidebar_widget post_category_widget">
    <h4 class="widget_title">Category</h4>
    <ul class="list cat-list">
        {% for c in category %}
        <li>
            <a href="{% url "news:category" name='SPORT' %}" class="d-flex">
                <p>{{ c.name }}</p>
                <p>({{c.news_count}})</p>
            </a>
        </li>
        {% endfor %}
    </ul>
</aside>

templates/base/recent.html
{% load static %}
{% load humanize %} 
<style>
    #lol{
        max-width: 180px;
        max-height: 230px;
    }
</style>
<aside class="single_sidebar_widget popular_post_widget">
    <h3 class="widget_title">Recent Post</h3>
    {% for post in latest %}
    <div class="media post_item">
        <img id="lol" src="{{post.image.url}}" alt="post">
        <div class="media-body">
            <a href="{% url "news:detail" num=post.pk %}">
                <h3>{{post.title}}</h3>
            </a>
            <p>{{post.created_time|naturaltime}}</p>
        </div>
    </div>
    {% endfor %}
</aside>

templates/base/search.html
{% load static %}
<aside class="single_sidebar_widget search_widget">
    <form method='GET' action="{% url "news:search" %}">
        <div class="form-group">
            <div class="input-group mb-3">
                <input type="text" class="form-control" name='q' >
                <div class="input-group-append">
                    <button class="btns" type="button"><i class="ti-search"></i></button>
                </div>
            </div>
        </div>
        <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
            type="submit">Search</button>
    </form>
</aside>

templates/base/tags.html
<aside class="single_sidebar_widget tag_cloud_widget">
    <h4 class="widget_title">Tag Clouds</h4>
    <ul class="list">
        {% for tag in tags %}
        <li>
            <a href="{% url "news:tag" tag_name=tag.name %}">{{tag.name}}</a>
        </li>
        {% endfor %}
    </ul>
</aside>