accounts/urls.py
from django.urls import path
from . import views


app_name='account'
urlpatterns = [
    path('login/',views.login_view,name="login"),
    path('signup/',views.profileregister,name="signup"),
    path('logout/',views.logout_view,name="logout"),
    path('profile/',views.profile_view,name="profile"),
    path('profileedit/',views.ProfileEdit,name='edit'),


]

api/urls.py
from django.urls import path , include
from .views import NewsList , NewsDetail, UserDetail ,UserList
from rest_framework.authtoken.views import obtain_auth_token
#from api.views import RevokeToken
# from rest_framework_simplejwt import views as jwt_views
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView


urlpatterns = [
    path("news/",NewsList.as_view(), name="list"),
    path("news/<int:pk>/",NewsDetail.as_view(), name="detail"),
    path("user/",UserList.as_view(), name="user-list"),
    path("user/<int:pk>/",UserDetail.as_view(), name="user-detail"),
    path('rest-auth/', include('dj_rest_auth.urls')),
    path('rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

]

core/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('news/',include('news.urls')),
    path('account/',include('accounts.urls')),
    #when using token we dont need this
    #path('api-auth/', include('rest_framework.urls')),
    path("api/",include("api.urls")),

]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('news/',views.NewsListView.as_view(), name='news'),
    path('news-detail/<int:num>/',views.NewsDetailView.as_view() , name='detail'),
    path('category/<str:name>/',views.CategoryView.as_view() , name="category"),
    path('search/',views.SearchView.as_view() , name="search"),
    path('favorite/',views.FavoriteView, name='favorite'),
    path('save_favorite/<int:post_id>/', views.save_favorite, name='save_favorite'),
    path('tags/<str:tag_name>/',views.TagView.as_view() , name='tag')

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager , User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name="profile")
    profile_picture = models.ImageField(upload_to='pics/',default="pics/aks.jpg")
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(max_length=254)
    phone = models.CharField(max_length=15)
    address=models.TextField(default="12")
    man=1
    woman=2
    status_choices=((man,"man"),(woman,"woman"))
    Gender=models.IntegerField(choices=status_choices , default=man)


    def __str__(self):
        return self.user.username

accounts/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import UserProfile
from django.contrib.auth.forms import UserChangeForm


class ProfileRegisterForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    username= forms.CharField( max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)
    email= forms.EmailField(widget=forms.EmailInput)
    
    class Meta:
        model = UserProfile
        fields=['profile_picture','phone','Gender','address']
    


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model=UserProfile
        fields=['profile_picture','Gender','phone','address']


class UserEditForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        fields=['first_name','last_name','email']
    password=None

accounts/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.models import User
from django.contrib.auth import login , logout , authenticate
from django.contrib.auth.decorators import login_required
from .forms import  ProfileRegisterForm , ProfileEditForm ,UserEditForm
from .models import UserProfile
from django.http import HttpResponseRedirect
from django.urls import reverse
# from django.core.mail import send_mail
# from django.template.loader import render_to_string
# from django.utils.html import strip_tags
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
# from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import *

def login_view(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user=authenticate(request , username=username ,password=password)
        if user :
            login(request,user)
            return redirect('account:profile')
    return render(request,'accounts/login.html')



def logout_view(request):
    logout(request)
    return redirect('/')



def profileregister(request):
    if request.method == "POST":
        profileRegisterForm = ProfileRegisterForm(request.POST, request.FILES)
        if profileRegisterForm.is_valid():
            username = profileRegisterForm.cleaned_data["username"]
            if User.objects.filter(username=username).exists():
                context = {
                    "formData": profileRegisterForm,
                    "errorMessage": "Username already exists. Please choose a different username."
                }
                return render(request, "accounts/sign-up.html", context)

            user = User.objects.create_user(
                username=username,
                email=profileRegisterForm.cleaned_data['email'],
                password=profileRegisterForm.cleaned_data['password'],
                first_name=profileRegisterForm.cleaned_data['first_name'],
                last_name=profileRegisterForm.cleaned_data['last_name']
            )
            user.save()

            profilemodel = UserProfile(
                user=user,
                profile_picture=profileRegisterForm.cleaned_data['profile_picture'],
                Gender=profileRegisterForm.cleaned_data['Gender'],
                phone=profileRegisterForm.cleaned_data['phone'],
                address=profileRegisterForm.cleaned_data['address']
            )
            profilemodel.save()

            #send email
            # subject = 'Welcome to Our Site!'
            # html_message = render_to_string('emails/welcome_email.html', {'user': user})
            # plain_message = strip_tags(html_message)
            # from_email = 'your_email@gmail.com'
            # to = user.email

            # send_mail(subject, plain_message, from_email, [to], html_message=html_message)



            return HttpResponseRedirect(reverse("home:home"))
        else:
            print(profileRegisterForm.errors)
    else:
        profileRegisterForm = ProfileRegisterForm()

    context = {
        "formData": profileRegisterForm
    }

    return render(request, "accounts/sign-up.html", context)




@login_required
def profile_view(request):
    profile=request.user.profile
    photo=request.user.profile.profile_picture

    context = {
        "profile" : profile,
        "photo" : photo,
    }
    return render(request,'accounts/profile.html',context)



def ProfileEdit(request):
    if request.method=="POST":
        profileEditForm = ProfileEditForm(request.POST,request.FILES,instance=request.user.profile)
        userEditForm=UserEditForm(request.POST,instance=request.user)
        if profileEditForm.is_valid and userEditForm.is_valid:
            profileEditForm.save()
            userEditForm.save()
            return HttpResponseRedirect(reverse("account:profile"))
    else:
        profileEditForm=ProfileEditForm(instance=request.user.profile)
        userEditForm=UserEditForm(instance=request.user)


    context={
        "profileEditForm":profileEditForm,
        'userEditForm':userEditForm,
        'profileImage':request.user.profile.profile_picture,
    }

    return render(request,"accounts/Edit.html",context)

templates/accounts/edit.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Creative Colorlib SignUp Form</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link href="{% static 'assets/css/style.css' %}" rel="stylesheet"  type="text/css" media="all" />
<!-- //Custom Theme files -->
<!-- web font -->
<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- //web font -->
<link href="{% static 'assets/css/stylesign.css' %}" rel="stylesheet"   />
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative SignUp Form</h1>
		<div class="main-agileinfo">
			<div class="agileits-top">
				<form action="{% url "account:edit" %}" method="post">
                    {% csrf_token %}
					{% comment %} <div class="form-group">
						<label for="first_name">Name:</label>
						{{formData.first_name}}
					</div>
			
					<div class="form-group">
						<label for="last_name">Family:</label>
						{{formData.last_name}}
					</div>
			
					<div class="form-group">
						<label for="email">Email:</label>
						{{formData.email}}
					</div>
			
					<div class="form-group">
						<label for="phone">Phone:</label>
						{{formData.phone}}
					</div>
			
					
			
					<div class="form-group">
					  <label for="username">Username:</label>
					  {{formData.username}}
				  </div>
			
					<div class="form-group">
						<label for="password">Password:</label>
						{{formData.password}}
					</div>
			
					<div class="form-group">
						<label for="profile_picture">Profile Image:</label>
						{{formData.profile_picture}}
					</div>
			
					<div class="form-group">
						<button type="submit">Register</button>
					</div>  {% endcomment %}

                     <label >first name : {{ userEditForm.first_name }}</label><br>
					<label >last_name : {{ userEditForm.last_name }}</label><br>
					<label >Phone : {{ profileEditForm.phone }}</label><br>
					<label >Email : {{ userEditForm.email }}</label><br>
                    <label >Gender : {{ profileEditForm.Gender }}</label><br><br>
					<label >Address : {{ profileEditForm.address }}</label> <br>
					{% comment %} <label >Profile Image : {{ userEditForm.profile_picture }}</label> {% endcomment %}
                    {% comment %} <img style="max-width:200px " src='{{ profileImage.url }}'> {% endcomment %}
                    {% comment %} <label for="profileimage">Profile Image:</label>
                    {{ profileEditForm.profilepicture }} {% endcomment %}
					<input type="submit" value="EDIT">
				</form> 
                <form>
                
                
                </form>
				<p>Already have an Account? <a href="{% url "account:login" %}"> Login Now!</a></p>
			</div>
		</div>
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
</body>
</html>

templates/accounts/profile.html
{% extends "base/base.html" %}
{% load static %}
{% block head %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>News  HTML-5 Template </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="{% static "assets/img/favicon.ico" %}">
    
    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/ticker-style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">

  <!-- slider stylesheet -->
  
  <style>
    {% comment %} body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
  } {% endcomment %}

  {% comment %} header {
      background-color: #333;
      color: #fff;
      padding: 20px;
      text-align: center;
  } {% endcomment %}

  .profile-container {
      max-width: 800px;
      margin: 40px auto;
      border: 1px solid #ddd;
      border-radius: 8px;
      padding: 20px;
  }

  .profile-picture {
      width: 150px;
      height: 150px;
      border-radius: 50%;
      margin: 0 auto 20px;
      display: block;
      background-color: #ccc;
  }

  .profile-name {
      font-size: 24px;
      font-weight: bold;
      text-align: center;
      margin-bottom: 10px;
  }

  .profile-bio {
      font-size: 16px;
      text-align: center;
      margin-bottom: 20px;
  }

  .profile-info {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 10px;
  }

  .profile-info span {
      font-weight: bold;
  }

  .profile-button {
      background-color: #007bff;
      color: #fff;
      padding: 10px 20px;
      border: none;
      border-radius: 5px;
      cursor: pointer;
      font-size: 16px;
  }

  .profile-button:hover {
      background-color: #0056b3;
  }
  </style>

</head>
{% endblock head%}


{% block content %}
<div class="profile-container">
    <img class="profile-picture" src="{{ profile.profile_picture.url }}" alt="Profile Picture"> 
    <h2 class="profile-name">{{ profile.user.username }} </h2> 
    <!-- <p class="profile-bio">Web Developer | Frontend Enthusiast</p> -->


    <div class="profile-info">
        <span>Full Name:</span>
        <span>{{ profile.user.get_full_name }}</span>
    </div> 

    <div class="profile-info">
        <span>Email:</span>
        <span>{{ profile.user.email }}</span>
    </div> 
    <div class="profile-info">
        <span>Location:</span>
        <span>{{ profile.address }}</span>
    </div> 

     <div class="profile-info">
        <span>Phone Number:</span>
        <span>{{ profile.phone }}</span>
    </div> 

    <div class="profile-info">
        <span>Gender:</span>
          <span>{{profile.get_Gender_display }}</span>
    </div> 
     <a href="{% url 'account:edit' %}">
      <button class="profile-button">Edit Profile</button>
    </a> 
    <a href="{% url 'news:favorite' %}">
        <button style='background-color:green;' class="profile-button">Favorite</button>
    </a>
</div>
{% endblock content %}

{% block js %}
    <!-- All JS Custom Plugins Link Here here -->
    <script src="{% static './assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static './assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static './assets/js/popper.min.js' %}"></script>
    <script src="{% static './assets/js/bootstrap.min.js' %}"></script>
    <!-- Jquery Mobile Menu -->
    <script src="{% static './assets/js/jquery.slicknav.min.js' %}"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="{% static './assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static './assets/js/slick.min.js' %}"></script>
    <!-- Date Picker -->
    <script src="{% static './assets/js/gijgo.min.js' %}"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="{% static './assets/js/wow.min.js' %}"></script>
    <script src="{% static './assets/js/animated.headline.js' %}"></script>
    <script src="{% static './assets/js/jquery.magnific-popup.js' %}"></script>

    <!-- Breaking New Pluging -->
    <script src="{% static './assets/js/jquery.ticker.js' %}"></script>
    <script src="{% static './assets/js/site.js' %}"></script>

    <!-- Scrollup, nice-select, sticky -->
    <script src="{% static './assets/js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static './assets/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static './assets/js/jquery.sticky.js' %}"></script>
    
    <!-- contact js -->
    <script src="{% static './assets/js/contact.js' %}"></script>
    <script src="{% static './assets/js/jquery.form.js' %}"></script>
    <script src="{% static './assets/js/jquery.validate.min.js' %}"></script>
    <script src="{% static './assets/js/mail-script.js' %}"></script>
    <script src="{% static './assets/js/jquery.ajaxchimp.min.js' %}"></script>
    
    <!-- Jquery Plugins, main Jquery -->	
    <script src="{% static './assets/js/plugins.js' %}"></script>
    <script src="{% static './assets/js/main.js' %}"></script>
</body>
</html>
{% endblock js %}

templates/accounts/sign-up.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Creative Colorlib SignUp Form</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link href="{% static 'assets/css/style.css' %}" rel="stylesheet"  type="text/css" media="all" />
<!-- //Custom Theme files -->
<!-- web font -->
<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- //web font -->
<link href="{% static 'assets/css/stylesign.css' %}" rel="stylesheet"   />
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative SignUp Form</h1>
		<div class="main-agileinfo">
			<div class="agileits-top">
				<form action="{% url "account:signup" %}" method="post" enctype="multipart/form-data" >
                    {% csrf_token %}


					<div class="form-group"><br>
						<label for="first_name">Name:</label>
						{{formData.first_name}}
					</div>
			
					<div class="form-group"><br>
						<label for="last_name">Family:</label>
						{{formData.last_name}}
					</div>
			
					<div class="form-group"><br>
						<label for="email">Email:</label>
						{{formData.email}}
					</div>
			
					<div class="form-group"><br>
						<label for="phone">Phone:</label>
						{{formData.phone}}
					</div>
			
					<div class="form-group"><br>
					    <label for="username">address:</label>
					    {{formData.address}}
				    </div>


					<div class="form-group"><br>
					    <label for="username">gender:</label>
					    {{formData.Gender}}
				    </div>
			
					<div class="form-group"><br>
					    <label for="username">Username:</label>
					    {{formData.username}}
				    </div>
			
					<div class="form-group"><br>
						<label for="password">Password:</label>
						{{formData.password}}
					</div>
			
					<div class="form-group"><br>
						<label for="profile_picture">Profile Image:</label>
						{{formData.profile_picture}}
					</div>

						<div class="wthree-text">
						<div class="clear"> </div>
					
					<input type="submit" value="SIGNUP">
				</form> 
                <form>
                
                
                </form>
				<p>Already have an Account? <a href="{% url "account:login" %}"> Login Now!</a></p>
			</div>
		</div>
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		
	</div>
	<!-- //main -->
</body>
</html>