api/urls.py
from django.urls import path , include
from .views import NewsList , NewsDetail, UserDetail ,UserList
from rest_framework.authtoken.views import obtain_auth_token
#from api.views import RevokeToken
# from rest_framework_simplejwt import views as jwt_views
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView


urlpatterns = [
    path("news/",NewsList.as_view(), name="list"),
    path("news/<int:pk>/",NewsDetail.as_view(), name="detail"),
    path("user/",UserList.as_view(), name="user-list"),
    path("user/<int:pk>/",UserDetail.as_view(), name="user-detail"),
    path('rest-auth/', include('dj_rest_auth.urls')),
    path('rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

]

core/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('news/',include('news.urls')),
    path('account/',include('accounts.urls')),
    #when using token we dont need this
    #path('api-auth/', include('rest_framework.urls')),
    path("api/",include("api.urls")),

]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('news/',views.NewsListView.as_view(), name='news'),
    path('news-detail/<int:num>/',views.NewsDetailView.as_view() , name='detail'),
    path('category/<str:name>/',views.CategoryView.as_view() , name="category"),
    path('search/',views.SearchView.as_view() , name="search"),
    path('favorite/',views.FavoriteView, name='favorite'),
    path('save_favorite/<int:post_id>/', views.save_favorite, name='save_favorite'),
    path('tags/<str:tag_name>/',views.TagView.as_view() , name='tag')

]

news/models.py
from django.db import models
from django.contrib.auth.models import User

class News(models.Model) :
    title=models.CharField(max_length=225)
    image=models.ImageField(upload_to='image/')
    created_time=models.DateTimeField(auto_now_add=True)
    updated_time=models.DateTimeField(auto_now=True)
    content=models.TextField()
    author=models.CharField(max_length=100)
    category=models.ManyToManyField("Category")
    tags = models.ManyToManyField("Tag")
    views_count = models.PositiveIntegerField(default=0)


    class Meta:
        verbose_name = "News"
        ordering = ["-created_time"]
        verbose_name_plural = "News"

    def __str__(self):
        return self.title
    

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    

class Comment(models.Model):
    post=models.ForeignKey(News,on_delete=models.CASCADE)
    name=models.CharField(max_length=255)
    email=models.EmailField()
    subject=models.CharField(max_length=255)
    message=models.TextField()
    created_time=models.DateTimeField(auto_now_add=True)
    Active=models.BooleanField(default=False)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering=['-created_time']



class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(News, on_delete=models.CASCADE)  # Assuming you have a Post model

    def __str__(self):
        return f"{self.user.username} - {self.post.title}"
    


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

news/forms.py
from django import forms
from .models import Comment , Favorite 


class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['post','name','email','subject','message']


class FovoriteForm(forms.ModelForm):
    class Mdta :
        model=Favorite
        fields='__all__'

news/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from .models import News, Category, Tag, Comment, Favorite
from .forms import CommentForm
from django.views import View
from django.contrib import messages

class BaseNewsView(View):
    def get_common_context(self):
        category = Category.objects.annotate(news_count=Count('news'))
        latest = News.objects.order_by('-created_time')[:4]
        tags = Tag.objects.all()[:10]
        return {
            'category': category,
            'latest': latest,
            'tags': tags
        }

class NewsListView(BaseNewsView):
    def get(self, request):
        news = News.objects.all()
        paginator = Paginator(news, 4)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = self.get_common_context()
        context.update({
            'news': news,
            'page_obj': page_obj
        })
        return render(request, "news/blog.html", context)

class NewsDetailView(BaseNewsView):
    def get(self, request, num):
        news = News.objects.get(pk=num)
        news.views_count += 1
        news.save()
        comments = Comment.objects.filter(post=news, Active=True)
        
        context = self.get_common_context()
        context.update({
            'news': news,
            'comments': comments,
            'form': CommentForm()
        })
        return render(request, "news/blog_details.html", context)

    def post(self, request, num):
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            print("Form is not valid:", form.errors)
            return self.get(request, num)  # Return the same page with errors

class CategoryView(BaseNewsView):
    def get(self, request, name):
        news = News.objects.filter(category__name=name)
        cat_count = Category.objects.count()
        
        context = self.get_common_context()
        context.update({
            'news': news,
            'name': name,
            'cat': cat_count
        })
        return render(request, "news/categori.html", context)

class SearchView(BaseNewsView):
    def get(self, request):
        query = request.GET.get('q', '')
        posts = News.objects.filter(content__icontains=query)
        
        context = self.get_common_context()
        context.update({"page_obj": posts})
        return render(request, 'news/blog.html', context)

@login_required
class FavoriteView(BaseNewsView):
    def get(self, request):
        saved = Favorite.objects.filter(user=request.user)
        paginator = Paginator(saved, 5)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        context = self.get_common_context()
        context.update({'page_obj': page_obj})
        return render(request, 'news/favorite.html', context)

@login_required
def save_favorite(request, post_id):
    user = request.user
    if not Favorite.objects.filter(user=user, post_id=post_id).exists():
        Favorite.objects.create(user=user, post_id=post_id)
        messages.success(request, 'Post saved as a favorite.')
    else:
        messages.warning(request, "Post is already saved as a favorite.")
    return redirect('news:news')

class TagView(BaseNewsView):
    def get(self, request, tag_name):
        # Fetch news articles related to the specified tag
        blog_tags = News.objects.filter(tags__name=tag_name)
        print(blog_tags)
        # Create the context with common items and specific blog tags
        context = self.get_common_context()
        context.update({
            'page_obg': blog_tags,  # Use 'blog_tags' instead of 'page_obj'
        })
        
        return render(request, 'news/tags.html', context)

templates/news/favorite.html
{% extends "base/base.html" %}
{% load static %}
{% block head %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>News  HTML-5 Template </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% comment %} <link rel="manifest" href="site.webmanifest"> {% endcomment %}
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/ticker-style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    
</head>
{% endblock head %}

{% block content %}
    <section class="blog_area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-5 mb-lg-0">
                    <div class="blog_left_sidebar">
                        {% for p in page_obj %}
                        <article class="blog_item">
                            <div class="blog_item_img">
                                <img class="card-img rounded-0" src="{{p.post.image.url}}" alt="">
                                <a href="#" class="blog_item_date">
                                    <h3>{{p.post.created_time|date:"d"}}</h3>
                                    <p>{{p.post.created_time|date:"D"}}</p>
                                </a>
                            </div>

                            <div class="blog_details">
                                <a class="d-inline-block" href="{% url "news:detail" num=p.post.id %}">
                                    <h2>{{p.post.title}}</h2>
                                </a>
                                <p>{{p.post.content|truncatewords:30}}</p>
                                <ul class="blog-info-link">
                                    <li><a href="#"><i class="fa fa-user"></i>
                                            {% for category in p.post.category.all %}
                                                {{ category.name }}
                                            {% if not forloop.last %}, {% endif %}
                                            {% endfor %}
                                    </a></li>
                                    <li><a href="#"><i class="fa fa-comments"></i> 03 Comments</a></li>
                                </ul>
                            </div>
                        </article>
                        {% endfor %}


                        
                        <nav class="blog-pagination justify-content-center d-flex">
                        
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a href="?page=1" class="page-link" aria-label="First">
                                        <i class="ti-angle-double-left"></i>
                                    </a>
                                </li>
                                <li class="page-item">
                                    <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
                                        <i class="ti-angle-left"></i>
                                    </a>
                                </li>
                                {% endif %}
                            
                                {% for i in page_obj.paginator.page_range %}
                                {% if page_obj.number == i %}
                                <li class="page-item active">
                                    <span class="page-link">{{ i }}</span>
                                </li>
                                {% else %}
                                <li class="page-item">
                                    <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                </li>
                                {% endif %}
                                {% endfor %}
                            
                                {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
                                        <i class="ti-angle-right"></i>
                                    </a>
                                </li>
                                <li class="page-item">
                                    <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link" aria-label="Last">
                                        <i class="ti-angle-double-right"></i>
                                    </a>
                                </li>
                                {% endif %}
                            </ul>
                            
                        </nav> 
                    
                    </div>
                </div>
                <div class="col-lg-4">
                    
                    <div class="blog_right_sidebar">

                        {% include "base/search.html" %}

                        {% include "base/category.html" %}
                        
                        {% include "base/recent.html" %}

                        {% include "base/tags.html" %} 


                        {% comment %} <aside class="single_sidebar_widget newsletter_widget">
                            <h4 class="widget_title">Newsletter</h4>

                            <form action="#">
                                <div class="form-group">
                                    <input type="email" class="form-control" onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Enter email'" placeholder='Enter email' required>
                                </div>
                                <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                    type="submit">Subscribe</button>
                            </form>
                        </aside> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->
    {% endblock content %}


    <script src="{% static './assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static './assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static './assets/js/popper.min.js' %}"></script>
    <script src="{% static './assets/js/bootstrap.min.js' %}"></script>
    <!-- Jquery Mobile Menu -->
    <script src="{% static './assets/js/jquery.slicknav.min.js' %}"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="{% static './assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static './assets/js/slick.min.js' %}"></script>

    <!-- One Page, Animated-HeadLin -->
    <script src="{% static './assets/js/wow.min.js' %}"></script>
    <script src="{% static './assets/js/animated.headline.js' %}"></script>
    
    <!-- Scrollup, nice-select, sticky -->
    <script src="{% static './assets/js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static './assets/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static './assets/js/jquery.sticky.js' %}"></script>
    <script src="{% static './assets/js/jquery.magnific-popup.js' %}"></script>

    <!-- contact js -->
    <script src="{% static './assets/js/contact.js' %}"></script>
    <script src="{% static './assets/js/jquery.form.js' %}"></script>
    <script src="{% static './assets/js/jquery.validate.min.js' %}"></script>
    <script src="{% static './assets/js/mail-script.js' %}"></script>
    <script src="{% static './assets/js/jquery.ajaxchimp.min.js' %}"></script>
    
    <!-- Jquery Plugins, main Jquery -->	
    <script src="{% static './assets/js/plugins.js' %}"></script>
    <script src="{% static './assets/js/main.js' %}"></script>

</body>
</html>

templates/news/tags.html
{% extends "base/base.html" %}
{% load cache %}
{% load static %}
{% load comment_tags %}
{% block head %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>News  HTML-5 Template </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% comment %} <link rel="manifest" href="site.webmanifest"> {% endcomment %}
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/ticker-style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <style>
        svg {
            position: relative;
            top: 25px; /* Adjust the top position */
            left: 700px; /* Adjust the left position */
        }
    
    </style>
</head>
{% endblock head %}
{% block content %}
    <section class="blog_area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-5 mb-lg-0">
                    <div class="blog_left_sidebar">
                        {% for post in page_obg %}
                        <article class="blog_item">
                            <div class="blog_item_img">
                                <img class="card-img rounded-0" src="{{post.image.url}}" alt="">
                                <a href="#" class="blog_item_date">
                                    <h3>{{post.created_time|date:"d"}}</h3>
                                    <p>{{post.created_time|date:"D"}}</p>
                                    
                                </a>
                                <a href="{% url "news:save_favorite" post_id=post.id %}" class="save-favorite-link" data-post-id="{{ post.id }}">
                                <svg xmlns="http://www.w3.org/2000/svg" height="2em" viewBox="0 0 384 512">
                                    <path d="M0 48C0 21.5 21.5 0 48 0l0 48V441.4l130.1-92.9c8.3-6 19.6-6 27.9 0L336 441.4V48H48V0H336c26.5 0 48 21.5 48 48V488c0 9-5 17.2-13 21.3s-17.6 3.4-24.9-1.8L192 397.5 37.9 507.5c-7.3 5.2-16.9 5.9-24.9 1.8S0 497 0 488V48z"/></svg>                                </svg>
                                </a>
                                </div>

                            <div class="blog_details">
                                <a class="d-inline-block" href="{% url "news:detail" num=post.id %}">
                                    <h2>{{post.title}}</h2>
                                </a>

                                    

                                <p>{{post.content|truncatewords:30}}</p>
                                <ul class="blog-info-link">
                                    <li><a href="#"><i class="fa fa-user"></i>
                                            {% for category in post.category.all %}
                                                {{ category.name }}
                                            {% if not forloop.last %}, {% endif %}
                                            {% endfor %}
                                    </a></li>
                                    <li><a href="#"><i class="fa fa-comments"></i>{% get_comment_count post.id %} comment</a></li>
                                </ul>
                            </div>


                            <div style="position: fixed;
                            top: 0;
                            left: 0;
                            width: 100%;
                            {% comment %} background-color: lightgray; {% endcomment %}
                            {% comment %} padding: 10px; {% endcomment %}
                            z-index: 1;" 
                            class="messages">
                                {% for message in messages %}
                                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                                {% endfor %}
                            </div>


                        </article>
                        {% endfor %}


                        
                        <nav class="blog-pagination justify-content-center d-flex">
                        
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a href="?page=1" class="page-link" aria-label="First">
                                        <i class="ti-angle-double-left"></i>
                                    </a>
                                </li>
                                <li class="page-item">
                                    <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
                                        <i class="ti-angle-left"></i>
                                    </a>
                                </li>
                                {% endif %}
                            
                                {% for i in page_obj.paginator.page_range %}
                                {% if page_obj.number == i %}
                                <li class="page-item active">
                                    <span class="page-link">{{ i }}</span>
                                </li>
                                {% else %}
                                <li class="page-item">
                                    <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                </li>
                                {% endif %}
                                {% endfor %}
                            
                                {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
                                        <i class="ti-angle-right"></i>
                                    </a>
                                </li>
                                <li class="page-item">
                                    <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link" aria-label="Last">
                                        <i class="ti-angle-double-right"></i>
                                    </a>
                                </li>
                                {% endif %}
                            </ul>
                            
                        </nav> 
                    
                    </div>
                </div>
                <div class="col-lg-4">
                    
                    <div class="blog_right_sidebar">

                        {% include "base/search.html" %}

                        {% include "base/category.html" %}
                        
                        {% include "base/recent.html" %}

                        {% include "base/tags.html" %}


                        <aside class="single_sidebar_widget instagram_feeds">
                            <h4 class="widget_title">Instagram Feeds</h4>
                            <ul class="instagram_row flex-wrap">
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="{% static 'assets/img/post/post_5.png' %}" alt="">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="{% static 'assets/img/post/post_6.png' %}" alt="">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="{% static 'assets/img/post/post_7.png' %}" alt="">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="{% static 'assets/img/post/post_8.png' %}" alt="">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="{% static 'assets/img/post/post_9.png' %}" alt="">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="{% static 'assets/img/post/post_10.png' %}" alt="">
                                    </a>
                                </li>
                            </ul>
                        </aside>


                        
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->
    {% endblock content %}


    <script src="{% static './assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static './assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static './assets/js/popper.min.js' %}"></script>
    <script src="{% static './assets/js/bootstrap.min.js' %}"></script>
    <!-- Jquery Mobile Menu -->
    <script src="{% static './assets/js/jquery.slicknav.min.js' %}"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="{% static './assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static './assets/js/slick.min.js' %}"></script>

    <!-- One Page, Animated-HeadLin -->
    <script src="{% static './assets/js/wow.min.js' %}"></script>
    <script src="{% static './assets/js/animated.headline.js' %}"></script>
    
    <!-- Scrollup, nice-select, sticky -->
    <script src="{% static './assets/js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static './assets/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static './assets/js/jquery.sticky.js' %}"></script>
    <script src="{% static './assets/js/jquery.magnific-popup.js' %}"></script>

    <!-- contact js -->
    <script src="{% static './assets/js/contact.js' %}"></script>
    <script src="{% static './assets/js/jquery.form.js' %}"></script>
    <script src="{% static './assets/js/jquery.validate.min.js' %}"></script>
    <script src="{% static './assets/js/mail-script.js' %}"></script>
    <script src="{% static './assets/js/jquery.ajaxchimp.min.js' %}"></script>
    
    <!-- Jquery Plugins, main Jquery -->	
    <script src="{% static './assets/js/plugins.js' %}"></script>
    <script src="{% static './assets/js/main.js' %}"></script>

    <script>
        $(document).on('click', '.save-favorite-link', function (e) {
            e.preventDefault();  // Prevent the default link behavior
            const post_id = $(this).data('post-id');
            $.ajax({
                url: `/save_favorite/${post_id}/`,
                method: 'GET',  // You can also use POST
                success: function (data) {
                    alert(data.message); // Display success message
                },
                error: function (xhr, status, error) {
                    console.log(error);
                }
            });
        });


    </script>
    
</body>
</html>